/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetTradesRouteImport } from './routes/getTrades'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiPullsRouteImport } from './routes/api/pulls'
import { Route as ApiTradesRouteImport } from './routes/api/trades'
import { Route as ApiPullsJobIdRouteImport } from './routes/api/pulls.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetTradesRoute = GetTradesRouteImport.update({
  id: '/getTrades',
  path: '/getTrades',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullsRoute = ApiPullsRouteImport.update({
  id: '/api/pulls',
  path: '/api/pulls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTradesRoute = ApiTradesRouteImport.update({
  id: '/api/trades',
  path: '/api/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPullsJobIdRoute = ApiPullsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiPullsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/getTrades': typeof GetTradesRoute
  '/health': typeof HealthRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pulls': typeof ApiPullsRouteWithChildren
  '/api/trades': typeof ApiTradesRoute
  '/api/pulls/$jobId': typeof ApiPullsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/getTrades': typeof GetTradesRoute
  '/health': typeof HealthRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pulls': typeof ApiPullsRouteWithChildren
  '/api/trades': typeof ApiTradesRoute
  '/api/pulls/$jobId': typeof ApiPullsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/getTrades': typeof GetTradesRoute
  '/health': typeof HealthRoute
  '/api/events': typeof ApiEventsRoute
  '/api/pulls': typeof ApiPullsRouteWithChildren
  '/api/trades': typeof ApiTradesRoute
  '/api/pulls/$jobId': typeof ApiPullsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/getTrades'
    | '/health'
    | '/api/events'
    | '/api/pulls'
    | '/api/trades'
    | '/api/pulls/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/getTrades'
    | '/health'
    | '/api/events'
    | '/api/pulls'
    | '/api/trades'
    | '/api/pulls/$jobId'
  id:
    | '__root__'
    | '/'
    | '/getTrades'
    | '/health'
    | '/api/events'
    | '/api/pulls'
    | '/api/trades'
    | '/api/pulls/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetTradesRoute: typeof GetTradesRoute
  HealthRoute: typeof HealthRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiPullsRoute: typeof ApiPullsRouteWithChildren
  ApiTradesRoute: typeof ApiTradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getTrades': {
      id: '/getTrades'
      path: '/getTrades'
      fullPath: '/getTrades'
      preLoaderRoute: typeof GetTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulls': {
      id: '/api/pulls'
      path: '/api/pulls'
      fullPath: '/api/pulls'
      preLoaderRoute: typeof ApiPullsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trades': {
      id: '/api/trades'
      path: '/api/trades'
      fullPath: '/api/trades'
      preLoaderRoute: typeof ApiTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pulls/$jobId': {
      id: '/api/pulls/$jobId'
      path: '/$jobId'
      fullPath: '/api/pulls/$jobId'
      preLoaderRoute: typeof ApiPullsJobIdRouteImport
      parentRoute: typeof ApiPullsRoute
    }
  }
}

interface ApiPullsRouteChildren {
  ApiPullsJobIdRoute: typeof ApiPullsJobIdRoute
}

const ApiPullsRouteChildren: ApiPullsRouteChildren = {
  ApiPullsJobIdRoute: ApiPullsJobIdRoute,
}

const ApiPullsRouteWithChildren = ApiPullsRoute._addFileChildren(
  ApiPullsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetTradesRoute: GetTradesRoute,
  HealthRoute: HealthRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiPullsRoute: ApiPullsRouteWithChildren,
  ApiTradesRoute: ApiTradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
